### ISSUE TITLE
MoveApps doesn't seem to allow caching osmnx data

### ISSUE THREAD

**Issue by arky** [arky/humaninfra-wildlife-interactions#4]
OSMNx caching failure. 

```
     2023-06-16 18:22:08.076: Running Stop Detector
     2023-06-16 18:22:14.773: Detected 1508 Stop Points.
     2023-06-16 18:22:14.774: Running Network Data Routine
     2023-06-16 18:22:15.868: storing error to /tmp/error_file.txt
     2023-06-16 18:22:15.868: Traceback (most recent call last):
     2023-06-16 18:22:15.868:   File "/opt/co-pilot-python/sdk.py", line 30, in <module>
     2023-06-16 18:22:15.868:     sdk = MoveAppsSdk(active_hooks=hooks)
     2023-06-16 18:22:15.868:   File "/opt/co-pilot-python/sdk.py", line 23, in __init__
     2023-06-16 18:22:15.868:     executor.execute()
     2023-06-16 18:22:15.869:   File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 33, in execute
     2023-06-16 18:22:15.869:     raise exception
     2023-06-16 18:22:15.869:   File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 29, in execute
     2023-06-16 18:22:15.869:     output = self.__call_app(data)
     2023-06-16 18:22:15.869:   File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 76, in __call_app
     2023-06-16 18:22:15.869:     outputs = self._pm.hook.execute(data=data, config=self.env.app_configuration)
     2023-06-16 18:22:15.869:   File "/opt/conda/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
     2023-06-16 18:22:15.869:     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
     2023-06-16 18:22:15.869:   File "/opt/conda/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
     2023-06-16 18:22:15.870:     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
     2023-06-16 18:22:15.870:   File "/opt/conda/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
     2023-06-16 18:22:15.870:     return outcome.get_result()
     2023-06-16 18:22:15.870:   File "/opt/conda/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
     2023-06-16 18:22:15.870:     raise ex[1].with_traceback(ex[2])
     2023-06-16 18:22:15.870:   File "/opt/conda/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
     2023-06-16 18:22:15.870:     res = hook_impl.function(*args)
     2023-06-16 18:22:15.870:   File "/opt/co-pilot-python/app/app.py", line 54, in execute
     2023-06-16 18:22:15.870:     G = ox.graph_from_bbox(maxy+buffer, miny-buffer, minx-buffer, maxx+buffer, network_type='drive', custom_filter=cf)
     2023-06-16 18:22:15.870:   File "/opt/conda/lib/python3.10/site-packages/osmnx/graph.py", line 85, in graph_from_bbox
     2023-06-16 18:22:15.870:     G = graph_from_polygon(
     2023-06-16 18:22:15.870:   File "/opt/conda/lib/python3.10/site-packages/osmnx/graph.py", line 432, in graph_from_polygon
     2023-06-16 18:22:15.870:     response_jsons = downloader._osm_network_download(poly_buff, network_type, custom_filter)
     2023-06-16 18:22:15.871:   File "/opt/conda/lib/python3.10/site-packages/osmnx/downloader.py", line 559, in _osm_network_download
     2023-06-16 18:22:15.871:     response_json = overpass_request(data={"data": query_str})
     2023-06-16 18:22:15.871:   File "/opt/conda/lib/python3.10/site-packages/osmnx/downloader.py", line 814, in overpass_request
     2023-06-16 18:22:15.871:     _save_to_cache(prepared_url, response_json, sc)
     2023-06-16 18:22:15.871:   File "/opt/conda/lib/python3.10/site-packages/osmnx/downloader.py", line 150, in _save_to_cache
     2023-06-16 18:22:15.871:     cache_folder.mkdir(parents=True, exist_ok=True)
     2023-06-16 18:22:15.871:   File "/opt/conda/lib/python3.10/pathlib.py", line 1175, in mkdir
     2023-06-16 18:22:15.871:     self._accessor.mkdir(self, mode)
     2023-06-16 18:22:15.871: PermissionError: [Errno 13] Permission denied: 'cache'
```

**Comment by andreakoelzsch** [comment]
Hi Arky,
I was also just wanting to let you know about an error with your App in MoveApps that sounds very similar. It seems that your App need some extra permissions for caching, Apps do not have root rights most of the time, as far as I understood. Caching has not come up in other other App so far. Probably worth to discuss with @cleemansen on Monday and see what we can do.
We will let you know what comes out of that.

**Comment by arky** [comment]
@andreakoelzsch  Perhaps in the long run having some way to cache would enable MoveApps be more efficient. Similar to how github enables caching packages and artifacts. https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows


@cleemansen Perhaps the simple solution is declare the cache location either to /tmp which is generally writeable in docker containers?  But I am not sure if that would be picked up in the next run of the workflow. Generally /tmp gets cleaned on container restarts unlike persistent volumes.

`ox.settings.cache_folder = "/tmp/cache"`

**Comment by cleemansen** [comment]
Hello, there is no persistent storage available for the apps (apart from storing app artifacts). Each app start begins with a fresh file system.

You should have write permissions from your app to the `/tmp` directory. You also have the option of setting environment variables via Python (if this happens not too late for `osmnx` cache setup).
So if your app would already benefit from `osmnx` caching during an isolated run, this should currently be configurable.

In general a global cache is a good idea - however the details would need to be discussed (multi user environment, privacy concerns, mutli app environment, cache eviction, etc)

Best

**Comment by andreakoelzsch** [comment]
@arky Hi Arky, after some discussion with Clemens, I would like to ask you to take out the OSM caching from the App for now. Adapting the MoveApps system to allow for it would be too costly for use now. Still, we see the advantage of it for use with OSM, I would suggest to have a group discussion about OSM at the workshop in September, discussing all the experiences and facettes of it will surely help us find the best solution. But first, please let us get your App working. Best, Andrea

**Comment by arky** [comment]
@andreakoelzsch Thank you! I have turned off the setting and request a new build now.
